org: brucethemaster
app: serverless-github-pullrequest-rest-api
service: serverless-github-pullrequest-rest-api

frameworkVersion: '2'

plugins:
  - serverless-bundle
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1
  apiName: ${self:service}
  memorySize: 256 # mb
  timeout: 10 # sec

functions:
  get:
    handler: handler.getPullRequest
    events:
      - http:
          path: pullrequests/{user}/{repository}/pulls
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                state: true
              paths:
                user: true
                repository: true
  healthcheck:
    handler: handler.healthCheck
    events:
      - http:
          path: healthcheck
          method: get
          cors: true
