service: serverless-github-pullrequest-rest-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1
  apiName: ${self:service}
  memorySize: 256 # mb
  timeout: 10

functions:
  view:
    handler: handler.getPullRequest
    events:
      - http:
          path: pullrequests/{user}/{repository}/pulls
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                state: true
              paths:
                user: true
                repository: true
